warnings_are_errors: false
language: node_js
node_js:
  - "10.15.0"
script:
 - cd site
 - CI=false yarn
 - CI=false yarn build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project real-infrastructure --only hosting:estereal --token $FIREBASE_TOKEN
