warnings_are_errors: false
language: node_js
node_js:
  - "10.15.0"
script:
 - set CI=false
 - cd site
 - yarn
 - yarn build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project real-infrastructure --token $FIREBASE_TOKEN
